### ISSUE TITLE
Непрерывная интеграция через ShareLatex

### ISSUE THREAD

**Issue by ulysses4ever** [geo2a/bachelor#2]
[Дублирую](https://github.com/siamezzze/bachelor_presentation/issues/1).

**Comment by geo2a** [comment]
Или я чего-то не понимаю, или там только 7 дней бесплатна интеграция с гитхабом, а потом денег хотят.

**Comment by geo2a** [comment]
О, я кажется разобрался. Перепутал с редактором.  Сейчас сделаю.

**Comment by geo2a** [comment]
С презентацией ничего не вышло, там lhs2tex. Сделал интеграцию только для текста работы.

**Comment by ulysses4ever** [comment]
А, я думал, у вас уже и в тексте lhs :)  Для такого дела (оно на самом деле сильно повышает доступность ваших работ) можно было бы даже генерируемый lhs2tex tex-файл добавить в реп. Ну, смотрите…

**Comment by geo2a** [comment]
Я вынес презентацию в отдельный [репозиторий](https://github.com/geo2a/bachelor-slides), но там пока ci не налажена: sharelatex сообщает об успешном билде, но в результирующей пдфке мусор, судя по логу что-то не так со шрифтами, работаю над этим.

**Comment by ulysses4ever** [comment]
Шрифты из презентации на НН мне пришлось отдельно ставить, да. Может, и не
взлетит. На самом деле, текст намного важней.
18 июня 2015 г. 21:32 пользователь "Georgiy Lukjanov" <
notifications@github.com> написал:
